logo: favicon.svg
locale: en_US
title: OpenOrchid
description: Discover new things.
search: true
env: dev

config:
  dev:
    url: http://127.0.0.1:5500/
  prod:
    url: https://openorchid.github.io/

url: site.config[site.env].url